[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dnnf"
author = "David Shriver"
author-email = "dls2fc@virginia.edu"
home-page = "https://github.com/dlshriver/DNNF"
description-file = "README.rst"
requires = [
    "dnnv~=0.4",
    "numpy>=1.16",
    "onnx>=1.7",
    "scipy>=1.5",
    "torch>=1.6",
    "torchvision>=0.7",
    "tensorflow<2.0",
]
requires-python = ">=3.7"

[tool.flit.metadata.requires-extra]
cleverhans = ["cleverhans==3.0.1"]
foolbox = ["foolbox~=3.3"]
dev = ["black", "mypy"]
doc = ["sphinx==2.4"]
test = ["coverage"]

[tool.flit.scripts]
dnnf = "dnnf.__main__:__main__"

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing", "thread"]
parallel = true
source = ["dnnf"]
